image:
  file: Dockerfile
tasks:
  - name: RPCiege
    before: |
      echo "source <(soroban completion --shell bash)" >> ~/.bashrc
    command: |
      soroban config identity generate player --global
      soroban config identity fund player --global --network futurenet
      soroban config network add rpciege --global --rpc-url "https://futurenet.rpciege.com" --network-passphrase "Test SDF Future Network ; October 2022"
      clear
      exit
vscode:
  extensions:
    - EthanSK.restore-terminals